apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-binding
spec:
  params:
    - name: url
      value: $(body.url)
    - name: robot-file
      value: $(body.robot-file)
